batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition\202501051701
train_epochs: 1000
train_workers: 20
vocab: 't?3M)I5l;FEGu''4R(ObwQPLVTd0XhgmD1e"ZWnBq+vU!-afr6Y/cK2*j8s7xiNJyHAop#9,.&CzkS:'
width: 128
